// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLVewkSAurzbKqNDSQ81xRJhMmkIdxS2Q',
    appId: '1:338437397831:web:4514e268ed934646680062',
    messagingSenderId: '338437397831',
    projectId: 'userdatabase-be5e3',
    authDomain: 'userdatabase-be5e3.firebaseapp.com',
    storageBucket: 'userdatabase-be5e3.appspot.com',
    measurementId: 'G-PKF0V6WL08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNN2rbd2cnvi174W8gAj_tmComSUaePQ',
    appId: '1:338437397831:android:0699354f4b6c92f5680062',
    messagingSenderId: '338437397831',
    projectId: 'userdatabase-be5e3',
    storageBucket: 'userdatabase-be5e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRIabV9OG5uMDztSR-pVoKdshUCuBMxPA',
    appId: '1:338437397831:ios:a9f8ef6773357fbe680062',
    messagingSenderId: '338437397831',
    projectId: 'userdatabase-be5e3',
    storageBucket: 'userdatabase-be5e3.appspot.com',
    iosBundleId: 'com.example.totalxtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRIabV9OG5uMDztSR-pVoKdshUCuBMxPA',
    appId: '1:338437397831:ios:a9f8ef6773357fbe680062',
    messagingSenderId: '338437397831',
    projectId: 'userdatabase-be5e3',
    storageBucket: 'userdatabase-be5e3.appspot.com',
    iosBundleId: 'com.example.totalxtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLVewkSAurzbKqNDSQ81xRJhMmkIdxS2Q',
    appId: '1:338437397831:web:3d667fd55f92a39d680062',
    messagingSenderId: '338437397831',
    projectId: 'userdatabase-be5e3',
    authDomain: 'userdatabase-be5e3.firebaseapp.com',
    storageBucket: 'userdatabase-be5e3.appspot.com',
    measurementId: 'G-5EJH35ZTPF',
  );
}
